project_id = "evkypmrihrgmvqejqxfe"

[functions.process-mpesa-payment]
verify_jwt = false

[functions.process-emola-payment]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.create-seller]
verify_jwt = false

[functions.ai-business-insights]
verify_jwt = false

[functions.process-payout]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.poultry-ai-insights]
verify_jwt = false

[functions.collect-environmental-data]
verify_jwt = false

[functions.system-audit]
verify_jwt = false
