// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Useful to verify the MCP connection is working.",
  inputSchema: {
    text: z.string().min(1).describe("Text to echo back.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/app-info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var app_info_default = defineTool2({
  name: "app_info",
  title: "App info",
  description: "Return basic information about the Navanhula Cloud app exposed via MCP.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify({
          name: "Navanhula Cloud",
          description: "Sistema Empresarial / Plataforma de Gest\xE3o (POS, estoque, fiscal, RH, agricultura, avicultura).",
          modules: [
            "POS",
            "Caixa",
            "Produtos",
            "Estoque",
            "Vendas",
            "Relat\xF3rios",
            "Financeiro",
            "RH",
            "Fiscal",
            "CRM",
            "BI",
            "Agricultura",
            "Avicultura"
          ]
        })
      }
    ]
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "navanhula-cloud-mcp",
  title: "Navanhula Cloud MCP",
  version: "0.1.0",
  instructions: "Tools exposed by the Navanhula Cloud business platform. Use `echo` to verify connectivity and `app_info` to discover available modules.",
  tools: [echo_default, app_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
